language: java
os: linux
jdk:
    - oraclejdk15

services:
    - docker

install: true

before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)

script:
    - docker build -t genshinwishes/genshin-wishes-api:$VERSION .
    - docker push genshinwishes/genshin-wishes-api:$VERSION

before_deploy:
    - git tag $VERSION

deploy:
    provider: releases
