app:
    client-url: ${CLIENT_URL}
    read-timeout: 120000
    connect-timeout: 120000
    oauth2:
        redirectUri: "${app.client-url}/login/oauth2/callback/{registrationId}"
    mihoyo:
        region-settings:
            hk4e_cn:
                im-endpoint: "https://api-takumi.mihoyo.com"
                wish-endpoint: "https://hk4e-api.mihoyo.com"
            hk4e_global:
                im-endpoint: "https://api-os-takumi.mihoyo.com"
                wish-endpoint: "https://hk4e-api-os.mihoyo.com"



management:
    endpoints:
        web:
            exposure:
                include: info,health,prometheus

spring:
    redis:
        host: genshin-wishes-redis
        port: 6379
    session:
        store-type: redis
    jpa:
        properties:
            hibernate:
                enable_lazy_load_no_trans: true
    datasource:
        hikari:
            maxLifetime: 60000
        url: ${JDBC_DATABASE_URL}
        username: ${JDBC_DATABASE_USERNAME}
        password: ${JDBC_DATABASE_PASSWORD}
    security:
        oauth2:
            client:
                registration:
                    facebook:
                        client-id: 3643805775683535
                        client-secret: ${FACEBOOK_SECRET}
                        redirect-uri: ${app.oauth2.redirectUri}
                        scope: email
                    google:
                        client-id: 431139673562-0676kbn3tpab8j6dml7nbrhvhj6e0432.apps.googleusercontent.com
                        client-secret: ${GOOGLE_SECRET}
                        redirect-uri: ${app.oauth2.redirectUri}
                    baidu:
                        client-id: xeuziiCgxY0QzcDe6BqCIwhb
                        client-secret: ${BAIDU_SECRET}
                        redirect-uri: ${app.oauth2.redirectUri}
                        authorizationGrantType: authorization_code
                        clientAuthenticationMethod: post
                        scope: basic
                        provider: baidu
                    discord:
                        client-id: 777998715255259167
                        client-secret: ${DISCORD_SECRET}
                        redirect-uri: ${app.oauth2.redirectUri}
                        authorizationGrantType: authorization_code
                        scope:
                            - identify
                            - email
                        provider: Discord
                provider:
                    facebook:
                        authorizationUri: https://www.facebook.com/v2.8/dialog/oauth?auth_type=rerequest
                    baidu:
                        authorizationUri: https://openapi.baidu.com/oauth/2.0/authorize
                        tokenUri: https://openapi.baidu.com/oauth/2.0/token
                        userInfoUri: https://openapi.baidu.com/rest/2.0/passport/users/getInfo
                        usernameAttribute: openid
                        userInfoAuthenticationMethod: form
                    Discord:
                        authorizationUri: https://discord.com/api/v8/oauth2/authorize
                        tokenUri: https://discord.com/api/v8/oauth2/token
                        userInfoUri: https://discord.com/api/v8/users/@me
                        usernameAttribute: username

logging:
    level:
        root: ERROR
        org.springframework.web: ERROR
        com.uf: INFO
